ci:
  collect:
    numberOfRuns: 3
  assert:
    assertions:
      categories:performance:
        - error
        - minScore: 0.9
      categories:accessibility:
        - error
        - minScore: 0.9
      categories:best-practices:
        - error
        - minScore: 0.9
      categories:seo:
        - error
        # TODO: Set back to 85 for launch. Issue #281
        - minScore: 0.80
      categories:pwa:
        - error
        - minScore: 0.9
